import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  subContainer: {
    marginHorizontal: 19,
  },
  password: {
    fontFamily: 'Poppins-Regular',
    fontSize: 24,
    fontWeight: '700',
    color: 'black',
  },
  numbers: {
    fontFamily: 'Poppins-Medium',
    fontSize: 18,
    fontWeight: '500',
    color: 'black',
  },
  numbers1: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    fontWeight: '500',
    color: 'black',
  },
  flex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 36,
  },
  input: {
    width: '100%',
    height: 58,
    borderColor: '#000000',
    borderWidth: 2,
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    borderRadius: 10,
    fontWeight: '700',
    paddingTop: 18,
    paddingBottom: 19,
    paddingLeft: 28,
    paddingRight: 19,
    marginTop: 64,
  },
  icon: {
    tintColor: 'black',
    position: 'absolute',
    right: 19,
    bottom: 15,
    width: 20,
    height: 20,
  },
  text: {
    fontSize: 14,
    fontWeight: '500',
    color: 'black',
    marginTop: 27,
  },
  button: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 200,
  },
  modaleBg: {
    backgroundColor: 'white',
    borderRadius: 20,
  },
  iconColor: {
    tintColor: 'white',
    width: 14,
    height: 14,
  },
  iconBg: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    width: 32,
    height: 32,
    borderRadius: 50,
    tintColor: 'white',
  },
  modalText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    fontWeight: '500',
    color: 'black',
    marginLeft: 50,
    marginRight: 50,
    marginTop: 27,
  },
  button1: {
    width: '80%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 54,
    marginLeft: 50,
    marginRight: 30,
  },
  align: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginRight: 20,
    marginTop: 18,
    marginBootm: 50,
  },
});
